---
layout: page
title: Intermediate programming with R
subtitle: dplyr
minutes: 10
---

> ## Learning Objectives {.objectives}
>


```{r}
library("dplyr")
```

```{r echo = FALSE}
counts_raw <- read.delim("data/counts-raw.txt.gz", stringsAsFactors = FALSE)
```

How does the total number of tweets change over the years?

```{r}
counts_raw %>%
  group_by(year) %>%
  summarize(total_tweets = sum(backtweetsCount))
```

And the Facebook likes?

```{r}
counts_raw %>%
  group_by(year) %>%
  summarize(total_tweets = sum(facebookLikeCount))
```

```{r}
counts_raw %>%
  group_by(year) %>%
  summarize(total_tweets = sum(facebookLikeCount, na.rm = TRUE))
```

In a function? How hard is it to convert this to use standard evaluation?

```{r}
test_se <- function(df, column) {
  x <- counts_raw %>%
  group_by_(~year) %>%
  summarize_(total_tweets = sum(facebookLikeCount, na.rm = TRUE))
}
```



```{r}
counts_raw %>%
  group_by(journal, year) %>%
  summarize(num = n())
```

```{r}
immuno <- filter(counts_raw, grepl("Immunology", plosSubjectTags))
```

```{r}
counts_raw %>%
  filter(grepl("Immunology", plosSubjectTags)) %>%
  group_by(journal, year) %>%
  summarize(num = n())
```

mean +/- sem

```{r}
tweets_per_journal <- counts_raw %>%
  group_by(journal) %>%
  summarize(mean = mean(backtweetsCount),
            sem = sd(backtweetsCount) / sqrt(n()),
            num = n())
```

```{r}
library("ggplot2")
ggplot(tweets_per_journal, aes(x = journal, y = mean)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean - sem, ymax = mean + sem)) +
  geom_text(aes(label = num), hjust = 1)
```

```{r}
tweets_per_journal <- counts_raw %>%
  group_by(journal, year) %>%
  summarize(mean = mean(backtweetsCount),
            sem = sd(backtweetsCount) / sqrt(n()),
            num = n())
```

```{r}
library("ggplot2")
ggplot(tweets_per_journal, aes(x = journal, y = mean)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean - sem, ymax = mean + sem)) +
  geom_text(aes(label = num), hjust = 1) +
  facet_wrap(~year)
```

```{r}
ggplot(tweets_per_journal, aes(x = journal, y = mean)) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = mean - sem, ymax = mean + sem)) +
  geom_text(aes(label = num), hjust = 1) +
  facet_wrap(~year)
```

